#!/usr/bin/env python3

import argparse
import json
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


def run(args, **kwargs):
    print('>', shlex.join(str(a) for a in args), flush=True)
    r = subprocess.run(args, **kwargs)
    if r.returncode != 0:
        sys.exit(r.returncode)
    return r


parser = argparse.ArgumentParser()
parser.add_argument('builddir', nargs='?', default='build', help='Build directory')

args = parser.parse_args()
build_dir = Path(args.builddir)

options = {
    opt['name']: opt['value']
    for opt in json.loads(run(['meson', 'introspect', build_dir, '--buildoptions'], capture_output=True).stdout)
}

base_dist_dir = build_dir / 'dist'
shutil.rmtree(base_dist_dir, True)

install_dir = base_dist_dir / 'install'
run(['meson', 'install', f'-C{build_dir}', f'--destdir={install_dir.relative_to(build_dir)}'])

dist_name = 'komankondi'
dist_dir = base_dist_dir / dist_name

bin_dir = install_dir.joinpath(*Path(options['prefix']).parts[1:], options['bindir'])
shutil.move(bin_dir, dist_dir)

if sys.platform == 'win32':
    run(['windeployqt', '--qmldir=src/ui', dist_dir / 'komankondi.exe'])

shutil.make_archive(str(build_dir / dist_name),
                    'zip' if sys.platform == 'win32' else 'xztar',
                    base_dist_dir,
                    dist_name,
                    owner='root',
                    group='root')
