= komankondi

komankondi is a game with one simple premise: you have to guess a word given its definition.


== Compiling

The game is expected to build on at least Linux and Windows; with the following commands:
----
cmake -G Ninja -B build
ninja -C build
----

This will attempt to install most dependencies via vcpkg and build the project with recommended optimizations.  You can customize this behavior via CMake options.


== Dictionary

Before playing you will need a komankondi dictionary.  This is nothing more than a database of words and their definition.  The easiest way to get one is to run the `komankondi-dictgen` tool.  It takes a source as argument, and currently only supports extracting the data from the https://wiktionary.org[wiktionary].  Prepend the desired language code; so for example to download data from the english (en) wiktionary you would execute the following:
----
komankondi-dictgen enwiktionary
----


== Playing

After all that you should be able to launch the game and have some fun!
