name: ci
on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, dev, debug]
    steps:
    - name: setup
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install meson qtdeclarative5-dev
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: configure
      env:
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      run: ./configure --buildtype=${{matrix.buildtype}} --flags=-Werror
    - name: build
      run: ninja -C build -k 0
    - name: test
      run: ninja -C build test
    - name: dist
      run: ./dist
    - name: upload dist
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{matrix.buildtype}}
        path: build/komankondi.tar.xz

  lint_linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
    steps:
    - name: setup
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install black meson pylint qtdeclarative5-dev
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: configure
      env:
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      run: ./configure --buildtype=${{matrix.buildtype}}
    - name: lint
      run: ./lint

  build_windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, dev, debug]
    steps:
    - name: setup
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: install
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin" >>"$env:GITHUB_PATH"
        pip install aqtinstall==3.1.7 meson==1.2.2 ninja==1.11.1
        aqt install-qt -O "$env:RUNNER_TEMP\qt" windows desktop 5.15.2 win64_msvc2019_64 --archives qtbase qtdeclarative qttools
        echo "$env:RUNNER_TEMP\qt\5.15.2\msvc2019_64\bin" >>"$env:GITHUB_PATH"
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: configure
      env:
        CXX: clang++
        CXX_LD: lld
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      run: python configure --buildtype=${{matrix.buildtype}} --flags=-Werror
    - name: build
      run: ninja -C build -k 0
    - name: test
      run: ninja -C build test
    - name: dist
      run: python dist
    - name: upload dist
      uses: actions/upload-artifact@v3
      with:
        name: windows-${{matrix.buildtype}}
        path: build/komankondi.zip

  lint_windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
    steps:
    - name: setup
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: install
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin" >>"$env:GITHUB_PATH"
        pip install aqtinstall==3.1.7 meson==1.2.2 ninja==1.11.1
        aqt install-qt -O "$env:RUNNER_TEMP\qt" windows desktop 5.15.2 win64_msvc2019_64 --archives qtbase qtdeclarative qttools
        echo "$env:RUNNER_TEMP\qt\5.15.2\msvc2019_64\bin" >>"$env:GITHUB_PATH"
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: configure
      env:
        CXX: clang++
        CXX_LD: lld
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      run: python configure --buildtype=${{matrix.buildtype}}
    - name: lint
      run: python lint clang-tidy
