name: dictgen
on:
  schedule:
    - cron: 0 3 3,22 * *
  workflow_dispatch:

jobs:
  dict:
    strategy:
      fail-fast: false
      matrix:
        source: [enwiktionary, frwiktionary]
    runs-on: ubuntu-latest
    container: "debian:bookworm"
    steps:
    - name: setup
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: install
      run: |
        apt-get update
        apt-get -y install g++ git meson ninja-build python3 qtdeclarative5-dev  \
          `#vcpkg:` cmake curl make pkg-config zip  \
          zstd
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: configure
      env:
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      run: ./configure
    - name: build
      run: ninja -C build src/dictgen/komankondi-dictgen
    - name: dictgen
      run: build/src/dictgen/komankondi-dictgen -o ${{matrix.source}}.dict ${{matrix.source}}
    - name: compress dict
      run: zstd -T0 ${{matrix.source}}.dict
    - name: upload dict
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.source}}
        path: ${{matrix.source}}.dict.zst
