name: linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
    steps:
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install meson
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/cache@v3
      with:
        key: vcpkg-${{hashFiles('.git/modules/vcpkg/HEAD')}}-${{hashFiles('vcpkg.json')}}
        path: ~/.cache/vcpkg
    - name: configure
      run: ./configure --buildtype ${{matrix.buildtype}} --werror
    - name: build
      run: ninja -C build -k 0
    - name: test
      run: ninja -C build test
    - name: format
      run: ninja -C build clang-format-check
    - name: tidy
      run: |
        tmp=$(mktemp -d)
        echo -e '#!/bin/sh\necho exec /usr/bin/clang-tidy --warnings-as-errors=* --extra-arg=-Wno-unknown-warning-option "$@"' >$tmp/clang-tidy
        chmod +x $tmp/clang-tidy
        PATH=$tmp:$PATH ninja -C build clang-tidy
