name: linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, dev, debug]
    steps:
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install meson qtdeclarative5-dev
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: setup vcpkg cache
      uses: actions/cache@v3
      with:
        key: vcpkg_${{hashFiles('vcpkg.json')}}_${{hashFiles('.git/modules/vcpkg/HEAD')}}_${{hashFiles('vcpkg_ports/**')}}
        path: ~/.cache/vcpkg
    - name: configure
      run: ./configure --buildtype=${{matrix.buildtype}} --flags=-Werror
    - name: build
      run: ninja -C build -k 0
    - name: test
      run: ninja -C build test
    - name: format
      run: ninja -C build clang-format-check
    - name: tidy
      run: |
        meson configure build -Dextra_warnings=false
        tmp=$(mktemp -d)
        echo -e '#!/bin/sh\necho exec /usr/bin/clang-tidy --warnings-as-errors=* "$@"' >$tmp/clang-tidy
        chmod +x $tmp/clang-tidy
        PATH="$tmp:$PATH" ninja -C build clang-tidy
    - name: upload build
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build (${{matrix.buildtype}})
        path: build
